//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.04 at 03:07:53 PM NZST 
//


package rabbit.data.internal.xml.schema.events;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for commandEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="activityEventType">
 *   &lt;complexContent>
 *     &lt;extension base="{}durationEventType">
 *       &lt;attribute name="activitySession" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="editSpeed" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "activityEventType")
public class ActivityEventType
    extends DurationEventType
{

    @XmlAttribute(required = true)
    protected String activitySession;
    @XmlAttribute(required = true)
    protected Double editSpeed;

    /**
     * Gets the value of the activitySession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivitySession() {
        return activitySession;
    }

    /**
     * Sets the value of the activitySession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivitySession(String value) {
        this.activitySession = value;
    }
    
    /**
     * Gets the value of the editSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Double getEditSpeed() {
        return editSpeed;
    }

    /**
     * Sets the value of the editSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditSpeed(Double value) {
        this.editSpeed = value;
    }

}
